AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Servless-2016-10-31
Description: Hello World with SAM

Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs16.x
    Timeout: 5

Resources:
  eventLogger:
    Type: AWS::Servless::Function
    Properties:
      Handler:  logger.handler
      Timeout: 3
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: get
          FileUpload:
            Type: S3
            Properties:
              Bucket: !Ref MyBucket
              Events: s3:ObjectCreated:*

  MyBucket:
    Type: AWS::S3::Bucket

  addNumber:
    Type: AWS::Servless::Function
    Properties:
      Handler:  add.handler
      Events:
        PostAdd:
          Type: Api
          Properties:
            Path: /add
            Method: post


